org.gradle.jvmargs=-Xmx2G
org.gradle.caching=false
org.gradle.caching.debug=false
#org.gradle.configureondemand=true
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true

mod.id=stargazer
mod.name=Stargazer
mod.version=0.0.9
mod.group=com.github.starcatcher21
mod.description=A Minecraft mod called Stargazer.

parchment_mappings_version=2024.11.17
