modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Starcatcher"
description = '''
${description}
'''
logoFile = "assets/${id}/icon.png"
logoBlur = false

[[mixins]]
config = "${id}.mixins.json"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersionVirtual},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "architectury"
type = "required"
versionRange = "[13.0.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "geckolib"
type = "required"
versionRange = "[4.9.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "starlib"
type = "required"
versionRange = "[1.0.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "roughlyenoughitems"
type = "optional"
versionRange = "[16.0.799,)"
ordering = "AFTER"
side = "CLIENT"
