package com.github.starcatcher21.stargazer.CreativeTab;

import com.github.starcatcher21.stargazer.Stargazer;
import com.github.starcatcher21.stargazer.block.ModBlock;
import com.github.starcatcher21.stargazer.block.register.*;
import com.github.starcatcher21.stargazer.item.ModItems;
import com.github.starcatcher21.stargazer.item.WishingStars;
import net.fabricmc.fabric.api.creativetab.v1.CreativeModeTabEvents;
import net.fabricmc.fabric.api.creativetab.v1.FabricCreativeModeTab;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.ItemStack;

public class ItemGroup {
    public static final ResourceKey<net.minecraft.world.item.CreativeModeTab> STAR_GROUP_KEY = ResourceKey.create(BuiltInRegistries.CREATIVE_MODE_TAB.key(), Identifier.fromNamespaceAndPath(Stargazer.MOD_ID, "star"));
    public static final net.minecraft.world.item.CreativeModeTab STAR_GROUP = FabricCreativeModeTab.builder()
            .icon(() -> new ItemStack(ModItems.YELLOW_STAR))
            .title(Component.translatable("itemGroup.Stargazer"))
            .build();

    public static void init() {
        Registry.register(BuiltInRegistries.CREATIVE_MODE_TAB, STAR_GROUP_KEY, STAR_GROUP);

        CreativeModeTabEvents.modifyOutputEvent(STAR_GROUP_KEY).register(itemGroup -> {
            itemGroup.accept(ModItems.STAR_BOOK);
            // Blocks
            itemGroup.accept(ModItems.STAR_HAMMER);
            itemGroup.accept(ModBlock.GRAVE);
            itemGroup.accept(ModBlock.NEGATIVE_BLOCK);
            itemGroup.accept(ModBlock.NORED_BLOCK);
            itemGroup.accept(ModBlock.NOGREEN_BLOCK);
            itemGroup.accept(ModBlock.NOBLUE_BLOCK);
            itemGroup.accept(ModBlock.INFESTED_CALCITE);
            itemGroup.accept(ModBlock.BONE_LEAVES);
            itemGroup.accept(ModBlock.SPRINKLER);
            itemGroup.accept(ModBlock.MOON_WELDER);
            // Crops
            itemGroup.accept(Crops.DRAGON_CARROT);
            itemGroup.accept(Crops.BROODY);
            itemGroup.accept(Crops.EYE_BALLS);
            // Fish
            itemGroup.accept(ModItems.GUMMY_FISH);
            itemGroup.accept(ModItems.GUMMY_WORM);
            itemGroup.accept(ModItems.COSMO_FISH);
            itemGroup.accept(ModItems.ENDER_FISH);
            itemGroup.accept(ModItems.GOLDEN_CRUCIAN);
            itemGroup.accept(ModItems.LUCKY_COMET);
            itemGroup.accept(ModItems.COMET_FRAGMENT);
            itemGroup.accept(MoonBlocks.COMET_BLOCK);
            itemGroup.accept(ModItems.AURORA_FRAGMENT);
            itemGroup.accept(StarBlocks.AURORA);
            itemGroup.accept(ModItems.MOON_COOKIE);
            itemGroup.accept(ModItems.STAR_COOKIE);
            // Star Blocks
            itemGroup.accept(StarBlocks.COSMIC_BLOCK);
            itemGroup.accept(StarBlocks.STAR_BARRIER_BLOCK);
            itemGroup.accept(StarBlocks.BORDER_BLOCK);
            itemGroup.accept(StarBlocks.STAR_LOG);
            itemGroup.accept(StarBlocks.STRIPPED_STAR_LOG);
            itemGroup.accept(StarBlocks.STAR_PLANKS);
            itemGroup.accept(StarBlocks.STAR_PLANKS_DOOR);
            itemGroup.accept(StarBlocks.STAR_PLANKS_SLAB);
            itemGroup.accept(StarBlocks.STAR_PLANKS_STAIRS);
            itemGroup.accept(StarBlocks.STAR_PLANKS_BUTTON);
            itemGroup.accept(StarBlocks.STAR_PLANKS_FENCE);
            itemGroup.accept(StarBlocks.STAR_PLANKS_FENCE_GATE);
            itemGroup.accept(StarBlocks.STAR_LEAVES);
            itemGroup.accept(StarBlocks.STAR_SAPLING);
            // Moon Rocks
            itemGroup.accept(MoonBlocks.MOON_ROCK);
            itemGroup.accept(MoonBlocks.POLISHED_MOON_ROCK);
            itemGroup.accept(MoonBlocks.MOON_ROCK_NYLIUM);
            itemGroup.accept(Darkness.DYLIUM);
            itemGroup.accept(Darkness.ROSE_OF_PAIN);
            itemGroup.accept(MoonBlocks.BLACK_MOON_ROCK);
            itemGroup.accept(MoonBlocks.POLISHED_BLACK_MOON_ROCK);
            itemGroup.accept(MoonBlocks.POLISHED_BLACK_MOON_ROCK_PURPLE);
            itemGroup.accept(MoonBlocks.MOON_ROCK_TILES);
            itemGroup.accept(MoonBlocks.PURPLE_MOON_ROCK_TILES);
            itemGroup.accept(MoonBlocks.MOON_ROCK_BRICKS);
            itemGroup.accept(MoonBlocks.MOON_ROCK_BRICKS_SLAB);
            itemGroup.accept(MoonBlocks.MOON_ROCK_BRICKS_STAIRS);
            itemGroup.accept(MoonBlocks.CRACKED_MOON_ROCK_BRICKS);
            itemGroup.accept(MoonBlocks.CHISELED_MOON_ROCK_BRICKS);
            itemGroup.accept(MoonBlocks.STAR_FORGE);
            itemGroup.accept(MoonBlocks.STAR_STONE);
            itemGroup.accept(MoonBlocks.PRISMATIC_ORE);
            itemGroup.accept(ModItems.PRISMATIC_SHARD);
            itemGroup.accept(MoonBlocks.PRISMATIC_SHARD_BLOCK);
            itemGroup.accept(ModItems.PRISMATIC_INGOT);
            itemGroup.accept(ModItems.MOON_GLASS_SHARD);
            itemGroup.accept(MoonBlocks.SUN_ENRICHED_MOON_ROCK);
            itemGroup.accept(MoonBlocks.POLISHED_SUN_ENRICHED_MOON_ROCK);
            itemGroup.accept(ModItems.SUN_ENRICHED_YELLOW_STAR);
            itemGroup.accept(WishingStars.WISHING_STAR);
            itemGroup.accept(WishingStars.WHITE_WISHING_STAR);
            itemGroup.accept(WishingStars.LIGHT_GRAY_WISHING_STAR);
            itemGroup.accept(WishingStars.GRAY_WISHING_STAR);
            itemGroup.accept(WishingStars.BLACK_WISHING_STAR);
            itemGroup.accept(WishingStars.BROWN_WISHING_STAR);
            itemGroup.accept(WishingStars.RED_WISHING_STAR);
            itemGroup.accept(WishingStars.ORANGE_WISHING_STAR);
            itemGroup.accept(WishingStars.LIME_WISHING_STAR);
            itemGroup.accept(WishingStars.GREEN_WISHING_STAR);
            itemGroup.accept(WishingStars.CYAN_WISHING_STAR);
            itemGroup.accept(WishingStars.LIGHT_BLUE_WISHING_STAR);
            itemGroup.accept(WishingStars.BLUE_WISHING_STAR);
            itemGroup.accept(WishingStars.PURPLE_WISHING_STAR);
            itemGroup.accept(WishingStars.MAGENTA_WISHING_STAR);
            itemGroup.accept(WishingStars.PINK_WISHING_STAR);
            itemGroup.accept(ModItems.DREAM_STAR);
            itemGroup.accept(ModItems.WINGED_STAR);
            itemGroup.accept(ModItems.THROWABLE_STAR);
            itemGroup.accept(StarBlocks.STAR_DISPLAY);
            // Moon Trees
            itemGroup.accept(MoonBlocks.MOON_LOG);
            itemGroup.accept(MoonBlocks.STRIPPED_MOON_LOG);
            itemGroup.accept(MoonBlocks.MOON_LEAVES);
            itemGroup.accept(MoonBlocks.MOON_SAPLING);
            itemGroup.accept(MoonBlocks.FULL_MOON_LOG);
            itemGroup.accept(MoonBlocks.FULL_MOON_LEAVES);
            itemGroup.accept(MoonBlocks.FULL_MOON_CORE);
            itemGroup.accept(MoonBlocks.FULL_MOON_SAPLING);
            itemGroup.accept(MoonBlocks.MOON_PLANKS);
            itemGroup.accept(MoonBlocks.MOON_PLANKS_DOOR);
            itemGroup.accept(MoonBlocks.MOON_PLANKS_SLAB);
            itemGroup.accept(MoonBlocks.MOON_PLANKS_STAIRS);
            itemGroup.accept(MoonBlocks.MOON_PLANKS_BUTTON);
            itemGroup.accept(MoonBlocks.MOON_PLANKS_FENCE);
            itemGroup.accept(MoonBlocks.MOON_PLANKS_FENCE_GATE);
            itemGroup.accept(MoonBlocks.PURPLE_MOON_PLANKS);
            itemGroup.accept(MoonBlocks.PURPLE_MOON_PLANKS_SLAB);
            itemGroup.accept(MoonBlocks.PURPLE_MOON_PLANKS_STAIRS);
            itemGroup.accept(MoonBlocks.PURPLE_MOON_PLANKS_BUTTON);
            itemGroup.accept(MoonBlocks.PURPLE_MOON_PLANKS_FENCE);
            itemGroup.accept(MoonBlocks.PURPLE_MOON_PLANKS_FENCE_GATE);
            itemGroup.accept(MoonBlocks.BLUE_MOON_PLANKS);
            itemGroup.accept(MoonBlocks.BLUE_MOON_PLANKS_SLAB);
            itemGroup.accept(MoonBlocks.BLUE_MOON_PLANKS_STAIRS);
            itemGroup.accept(MoonBlocks.BLUE_MOON_PLANKS_BUTTON);
            itemGroup.accept(MoonBlocks.BLUE_MOON_PLANKS_FENCE);
            itemGroup.accept(MoonBlocks.BLUE_MOON_PLANKS_FENCE_GATE);
            itemGroup.accept(MoonBlocks.RED_MOON_PLANKS);
            itemGroup.accept(MoonBlocks.RED_MOON_PLANKS_SLAB);
            itemGroup.accept(MoonBlocks.RED_MOON_PLANKS_STAIRS);
            itemGroup.accept(MoonBlocks.RED_MOON_PLANKS_BUTTON);
            itemGroup.accept(MoonBlocks.RED_MOON_PLANKS_FENCE);
            itemGroup.accept(MoonBlocks.RED_MOON_PLANKS_FENCE_GATE);
            itemGroup.accept(MoonBlocks.YELLOW_MOON_PLANKS);
            itemGroup.accept(MoonBlocks.YELLOW_MOON_PLANKS_SLAB);
            itemGroup.accept(MoonBlocks.YELLOW_MOON_PLANKS_STAIRS);
            itemGroup.accept(MoonBlocks.YELLOW_MOON_PLANKS_BUTTON);
            itemGroup.accept(MoonBlocks.YELLOW_MOON_PLANKS_FENCE);
            itemGroup.accept(MoonBlocks.YELLOW_MOON_PLANKS_FENCE_GATE);
            // curve tree
            itemGroup.accept(MoonBlocks.CURVE_LOG);
            itemGroup.accept(MoonBlocks.STRIPPED_CURVE_LOG);
            itemGroup.accept(MoonBlocks.CURVE_LEAVES);
            itemGroup.accept(MoonBlocks.CURVE_SAPLING);
            itemGroup.accept(MoonBlocks.CURVE_PLANKS);
            itemGroup.accept(MoonBlocks.CURVE_PLANKS_DOOR);
            itemGroup.accept(MoonBlocks.CURVE_PLANKS_SLAB);
            itemGroup.accept(MoonBlocks.CURVE_PLANKS_STAIRS);
            itemGroup.accept(MoonBlocks.CURVE_PLANKS_BUTTON);
            itemGroup.accept(MoonBlocks.CURVE_PLANKS_FENCE);
            itemGroup.accept(MoonBlocks.CURVE_PLANKS_FENCE_GATE);
            // mushroom
            itemGroup.accept(MoonBlocks.PURPLE_MUSHROOM);
            itemGroup.accept(MoonBlocks.PURPLE_MUSHROOM_BLOCK);
            // Eye
            itemGroup.accept(EyeBloodBlocks.EYE_LOG);
            itemGroup.accept(EyeBloodBlocks.STRIPPED_EYE_LOG);
            itemGroup.accept(EyeBloodBlocks.EYE_LEAVES);
            itemGroup.accept(EyeBloodBlocks.EYE_JAR);
            itemGroup.accept(ModItems.DEAD_EYE_BAT);
            itemGroup.accept(ModItems.LIVING_EYE);
            // Darkness
            itemGroup.accept(Darkness.LOG_OF_DARKNESS);
            itemGroup.accept(Darkness.STRIPPED_LOG_OF_DARKNESS);
            itemGroup.accept(Darkness.DARKNESS_LEAVES);
            itemGroup.accept(Darkness.DARKNESS_SAPLING);
            itemGroup.accept(Darkness.DARKNESS_PLANKS);
            itemGroup.accept(Darkness.DARKNESS_PLANKS_SLAB);
            itemGroup.accept(Darkness.DARKNESS_PLANKS_STAIRS);
            itemGroup.accept(Darkness.DARKNESS_PLANKS_BUTTON);
            itemGroup.accept(Darkness.DARKNESS_PLANKS_FENCE);
            itemGroup.accept(Darkness.DARKNESS_PLANKS_FENCE_GATE);
            // Plants
            itemGroup.accept(StarBlocks.STAR_FLOWER);
            itemGroup.accept(StarBlocks.CELESTIAL_STAR_FLOWER);
            itemGroup.accept(MoonBlocks.MOON_GRASS);
            itemGroup.accept(MoonBlocks.TALL_MOON_GRASS);
            itemGroup.accept(MoonBlocks.STAR_TRAP);
            itemGroup.accept(MoonBlocks.MOON_FERN);
            itemGroup.accept(MoonBlocks.FORGET_ME_NOW);
            itemGroup.accept(Darkness.GRADI);
            itemGroup.accept(EyeBloodBlocks.EYE_FERN);
            itemGroup.accept(EyeBloodBlocks.EYES);
            itemGroup.accept(Nebulas.PURPLE_TENTACLE_FLOWER);
            itemGroup.accept(Nebulas.BLUE_TENTACLE_FLOWER);
            itemGroup.accept(Nebulas.RED_TENTACLE_FLOWER);
            itemGroup.accept(Nebulas.YELLOW_TENTACLE_FLOWER);
            itemGroup.accept(MoonBlocks.SPRUNGUS);
            // Items
            itemGroup.accept(ModItems.STARDUST);
            itemGroup.accept(ModItems.PURPLE_STAR);
            itemGroup.accept(StarBlocks.PURPLE_STAR_BLOCK);
            itemGroup.accept(Nebulas.PURPLE_NEBULA_LOG);
            itemGroup.accept(Nebulas.PURPLE_NEBULA_PLANKS);
            itemGroup.accept(Nebulas.PURPLE_NEBULA_PLANKS_BUTTON);
            itemGroup.accept(Nebulas.PURPLE_NEBULA_PLANKS_FENCE);
            itemGroup.accept(Nebulas.PURPLE_NEBULA_PLANKS_FENCE_GATE);
            itemGroup.accept(Nebulas.PURPLE_NEBULA_PLANKS_SLAB);
            itemGroup.accept(Nebulas.PURPLE_NEBULA_PLANKS_STAIRS);
            itemGroup.accept(Nebulas.PURPLE_NEBULA_LEAVES);
            itemGroup.accept(Nebulas.PURPLE_NEBULA_REGROW_CORE);
            itemGroup.accept(ModItems.BLUE_STAR);
            itemGroup.accept(StarBlocks.BLUE_STAR_BLOCK);
            itemGroup.accept(Nebulas.BLUE_NEBULA_LOG);
            itemGroup.accept(Nebulas.BLUE_NEBULA_PLANKS);
            itemGroup.accept(Nebulas.BLUE_NEBULA_PLANKS_BUTTON);
            itemGroup.accept(Nebulas.BLUE_NEBULA_PLANKS_FENCE);
            itemGroup.accept(Nebulas.BLUE_NEBULA_PLANKS_FENCE_GATE);
            itemGroup.accept(Nebulas.BLUE_NEBULA_PLANKS_SLAB);
            itemGroup.accept(Nebulas.BLUE_NEBULA_PLANKS_STAIRS);
            itemGroup.accept(Nebulas.BLUE_NEBULA_LEAVES);
            itemGroup.accept(Nebulas.BLUE_NEBULA_REGROW_CORE);
            itemGroup.accept(ModItems.RED_STAR);
            itemGroup.accept(StarBlocks.RED_STAR_BLOCK);
            itemGroup.accept(Nebulas.RED_NEBULA_LOG);
            itemGroup.accept(Nebulas.RED_NEBULA_PLANKS);
            itemGroup.accept(Nebulas.RED_NEBULA_PLANKS_BUTTON);
            itemGroup.accept(Nebulas.RED_NEBULA_PLANKS_FENCE);
            itemGroup.accept(Nebulas.RED_NEBULA_PLANKS_FENCE_GATE);
            itemGroup.accept(Nebulas.RED_NEBULA_PLANKS_SLAB);
            itemGroup.accept(Nebulas.RED_NEBULA_PLANKS_STAIRS);
            itemGroup.accept(Nebulas.RED_NEBULA_LEAVES);
            itemGroup.accept(Nebulas.RED_NEBULA_REGROW_CORE);
            itemGroup.accept(ModItems.YELLOW_STAR);
            itemGroup.accept(StarBlocks.YELLOW_STAR_BLOCK);
            itemGroup.accept(Nebulas.YELLOW_NEBULA_LOG);
            itemGroup.accept(Nebulas.YELLOW_NEBULA_PLANKS);
            itemGroup.accept(Nebulas.YELLOW_NEBULA_PLANKS_BUTTON);
            itemGroup.accept(Nebulas.YELLOW_NEBULA_PLANKS_FENCE);
            itemGroup.accept(Nebulas.YELLOW_NEBULA_PLANKS_FENCE_GATE);
            itemGroup.accept(Nebulas.YELLOW_NEBULA_PLANKS_SLAB);
            itemGroup.accept(Nebulas.YELLOW_NEBULA_PLANKS_STAIRS);
            itemGroup.accept(Nebulas.YELLOW_NEBULA_LEAVES);
            itemGroup.accept(Nebulas.YELLOW_NEBULA_REGROW_CORE);
            itemGroup.accept(ModItems.LODESTAR);
            itemGroup.accept(ModItems.GEODE_FRUIT);
            itemGroup.accept(ModItems.COOKED_GEODE_FRUIT);
            itemGroup.accept(ModItems.FULL_COOKED_GEODE_FRUIT);
            itemGroup.accept(ModItems.BLACK_COOKED_GEODE_FRUIT);
            itemGroup.accept(ModItems.ECTOPLASM);
            itemGroup.accept(ModItems.COOLER_ECTOPLASM);
            itemGroup.accept(ModItems.STAR_BANNER_PATTERN);
            // SpawnEggs
            itemGroup.accept(ModItems.GHOST_SPAWN_EGG);
            itemGroup.accept(ModItems.AMETHYST_TURTLE_SPAWN_EGG);
            itemGroup.accept(ModItems.EYE_BAT_SPAWN_EGG);
            itemGroup.accept(ModItems.ROOK_SPAWN_EGG);
            itemGroup.accept(ModItems.BLACK_ROOK_SPAWN_EGG);
            itemGroup.accept(ModItems.SCRUBY_SPAWN_EGG);
            itemGroup.accept(ModItems.BLACK_FOX_SPAWN_EGG);
            // Chess
            itemGroup.accept(Chess.BLACK_CHESSBOARD);
            itemGroup.accept(Chess.WHITE_CHESSBOARD);
            itemGroup.accept(Chess.CHESSBOARD);
            itemGroup.accept(ModItems.WHITE_BRICK);
            itemGroup.accept(ModItems.BLACK_BRICK);
            itemGroup.accept(Chess.WHITE_BRICKS);
            itemGroup.accept(Chess.BLACK_BRICKS);
            // Hedge
            itemGroup.accept(Hedges.OAK_HEDGE);
            itemGroup.accept(Hedges.BIRCH_HEDGE);
            itemGroup.accept(Hedges.ACACIA_HEDGE);
            itemGroup.accept(Hedges.CHERRY_HEDGE);
            itemGroup.accept(Hedges.DARK_OAK_HEDGE);
            itemGroup.accept(Hedges.JUNGLE_HEDGE);
            itemGroup.accept(Hedges.MANGROVE_HEDGE);
            itemGroup.accept(Hedges.PALE_HEDGE);
            itemGroup.accept(Hedges.SPRUCE_HEDGE);
            itemGroup.accept(Hedges.MOON_HEDGE);
            itemGroup.accept(Hedges.CURVE_HEDGE);
            itemGroup.accept(Hedges.STAR_HEDGE);
            itemGroup.accept(Hedges.DARKNESS_HEDGE);
            itemGroup.accept(Hedges.YERI_HEDGE);
            itemGroup.accept(Hedges.SPIRO_HEDGE);
            itemGroup.accept(Hedges.TRUNN_HEDGE);
            // Red Orb
            itemGroup.accept(RedOrbBlocks.RED_ROCK);
            itemGroup.accept(RedOrbBlocks.RED_ROCK_SLAB);
            itemGroup.accept(RedOrbBlocks.RED_ROCK_STAIRS);
            itemGroup.accept(RedOrbBlocks.POLISHED_RED_ROCK);
            itemGroup.accept(RedOrbBlocks.YERI_LOG);
            itemGroup.accept(RedOrbBlocks.YERI_LEAVES);
            itemGroup.accept(RedOrbBlocks.YERI_SAPLING);
            itemGroup.accept(ModItems.RED_ORB_PLATFORM_BASE);
            itemGroup.accept(RedOrbBlocks.RED_ORB_PLATFORM);
            itemGroup.accept(RedOrbBlocks.GREEN_ROCK);
            itemGroup.accept(RedOrbBlocks.BLUE_GRASS);
            itemGroup.accept(RedOrbBlocks.POINTY);
            itemGroup.accept(RedOrbBlocks.SPIRO_LOG);
            itemGroup.accept(RedOrbBlocks.SPIRO_LEAVES);
            itemGroup.accept(RedOrbBlocks.SPIRO_SAPLING);
            // Wander
            itemGroup.accept(ModItems.DARKSTAR);
            itemGroup.accept(Wander.BORIL);
            itemGroup.accept(Wander.PUROIL);
            itemGroup.accept(Wander.TRUNN_LOG);
            itemGroup.accept(Wander.TRUNN_LEAVES);
            itemGroup.accept(Wander.TRUNN_SAPLING);
            itemGroup.accept(ModItems.DREAM_BUCKET);
            // Energy
            itemGroup.accept(Energy.STARMACHINE_BLOCK);
            itemGroup.accept(Energy.STARGENERATOR);
            itemGroup.accept(Energy.YELLOW_CABLE);
            itemGroup.accept(Energy.BLUE_CABLE);
            itemGroup.accept(Energy.RED_CABLE);
            itemGroup.accept(Energy.PURPLE_CABLE);
            itemGroup.accept(Energy.NIGHT_WATCHER);
            itemGroup.accept(Energy.STAR_CRUSHER);
            itemGroup.accept(ModItems.COPPER_DUST);
            itemGroup.accept(ModItems.IRON_DUST);
            itemGroup.accept(ModItems.GOLD_DUST);
            itemGroup.accept(ModItems.SUPERNOVA);
        });
    }
}
