modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "stargazer"
version = "${version}"
displayName = "Stargazer"
iconFile = "assets/stargazer/icon.png"
authors = "starcatcher"
description = '''
Gaze into the stars
'''

[[dependencies.stargazer]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stargazer]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,26.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stargazer]]
modId = "architectury"
type = "required"
versionRange = "[21.0.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stargazer]]
modId = "geckolib"
type = "required"
versionRange = "[5.5.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stargazer]]
modId = "starlib"
type = "required"
versionRange = "[1.0.3,)"
ordering = "NONE"
side = "BOTH"